<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="DESKTOP-L85IPM0" name="pytest" skipped="0" tests="6" time="0.110" timestamp="2020-08-31T16:00:25.278000"><testcase classname="test_example2-2-3" file="test_example2-2-3.py" line="12" name="test_add" time="0.010"><failure message="assert 8 == 7
 +  where 8 = &lt;bound method Calculator.add of &lt;calc.Calculator object at 0x0000000003EEDB48&gt;&gt;(5, 2)
 +    where &lt;bound method Calculator.add of &lt;calc.Calculator object at 0x0000000003EEDB48&gt;&gt; = &lt;calc.Calculator object at 0x0000000003EEDB48&gt;.add">calc = &lt;calc.Calculator object at 0x0000000003EEDB48&gt;

    def test_add(calc):
&gt;       assert calc.add(5, 2) == 7
E       assert 8 == 7
E        +  where 8 = &lt;bound method Calculator.add of &lt;calc.Calculator object at 0x0000000003EEDB48&gt;&gt;(5, 2)
E        +    where &lt;bound method Calculator.add of &lt;calc.Calculator object at 0x0000000003EEDB48&gt;&gt; = &lt;calc.Calculator object at 0x0000000003EEDB48&gt;.add

test_example2-2-3.py:14: AssertionError</failure></testcase><testcase classname="test_example2-2-3" file="test_example2-2-3.py" line="16" name="test_sub" time="0.000"></testcase><testcase classname="test_example2-2-3" file="test_example2-2-3.py" line="20" name="test_mul" time="0.000"></testcase><testcase classname="test_example2-2-3" file="test_example2-2-3.py" line="24" name="test_div" time="0.011"></testcase><testcase classname="test_example2-2-3" file="test_example2-2-3.py" line="28" name="test_square" time="0.000"></testcase><testcase classname="test_example2-2-3" file="test_example2-2-3.py" line="32" name="test_cube" time="0.000"></testcase></testsuite></testsuites>